Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
Resources:
  SecurityGroup:
     Type: AWS::EC2::SecurityGroup
     Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: '0.0.0.0/0'

  DirtyInstance:
    Type: AWS::EC2::Instance
    DependsOn: SecurityGroup
    Metadata:
      Comment: Cloud Custodian Config File
      AWS::CloudFormation::Init:
        config:
          files:
            /root/custodian.yml:
              content: !Sub |
                policies:
                  - name: keep-instance-policy
                    resource: ec2
                    filters:
                      - "tag:DirtyInstance": present
                    actions:
                      - terminate
              mode: "000400"
              owner: root
              group: root
    Properties:
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref SecurityGroup
      InstanceType: t2.micro
      ImageId: ami-22ce4934
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y aws-cfn-bootstrap
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource DirtyInstance --region ${AWS::Region}
          cd /root
          virtualenv custodian
          source source custodian/bin/activate
          pip install c7n
          custodian run --output-dir=. /root/custodian.yml
    Tags:
      - Key: DirtyInstance
        Value: yup
